#!/usr/bin/env node
var http = require('http');
var port = 1337;

console.log('EXAMPLE_ACCESS_KEY from .env file: ',process.env.EXAMPLE_ACCESS_KEY);
console.warn("Test Warning Message to stderr");

http.createServer(function(req, res) {
  res.writeHead(200, {
    'Content-Type': 'text/plain'
  });
  res.end('Hello World\n');
}).listen(port, '127.0.0.1');
console.log('Server running at http://127.0.0.1:%s', port);

